/*------------------------------------------------------------------------
    File        : ProcedureGenerator
    Purpose     : Generator class for Procedures.
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.
USING OEMock.Generation.BaseMethodGenerator.

ROUTINE-LEVEL ON ERROR UNDO, THROW.

CLASS OEMock.Generation.ProcedureGenerator INHERITS BaseMethodGenerator: 

END CLASS.